Version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn package
  post_build:
    commands:
    - ls
    - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
    - appspec.yml